### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by silvewheat** [ctlab/GADMA#23]
Hello,
  When I try to run GADMA, there is an error occurd:
![image](https://user-images.githubusercontent.com/19344997/98367201-30acf780-2070-11eb-87ac-5da1b752ba56.png)
  My parameter file is :
![image](https://user-images.githubusercontent.com/19344997/98367348-6baf2b00-2070-11eb-88f3-370fe443a8ca.png)

**Comment by silvewheat** [comment]
I noticed that there are lots of warnings. Is that related with the error?
![image](https://user-images.githubusercontent.com/19344997/98371046-7ec4f980-2076-11eb-9b3f-da636a24e9ca.png)

**Comment by silvewheat** [comment]
It seems that because my SFS file have too many zero. I'm checking now.

**Comment by silvewheat** [comment]
Is there someway to convert momi2 SFS file to dadi format?
Because I exclude some regions when calculate SFS, which is supported by momi2 but not easySFS.

**Comment by silvewheat** [comment]
I forgot the option -a when generate the SFS file using easySFS. That maybe the reason. I'm generating a new SFS file now. I'll tell you if the new SFS work.

**Comment by noscode** [comment]
Dear @silvewheat,

Thank you for your interest to GADMA and for bug report! This is actually wrong behavior and unexpected error, I will fix this in the next release. You are right it looks like AFS has a lot of zeros and this is the actual problem because as the result theta is very small and size of ancestral population becomes around zero and causes this error. Please keep me updated about your new AFS.

Best regards,
Ekaterina

**Comment by silvewheat** [comment]
GADMA now is running correctly when I using the new SFS file.
Thank you.
