### ISSUE TITLE
Estimating Theta0?

### ISSUE THREAD

**Issue by ChenSh1ne** [ctlab/GADMA#3]
Hi, Ekaterina Noskova,
I have a problem when I using gadma, in the manual, Theta0 = 4uL, but I don't know how to set L in config file, can u give some advices or get this value through other ways ? 

Yours,
ChenSh1ne

**Comment by noscode** [comment]
Hi, ChenSh1ne,

I am sorry for the delay. L is the effective sequence length. If you do not know it then you cannot estimate theta0 at all. In this case when you have data without knowing the length of genome that was used to get it, then unfortunately you can get demographic history only with relative to Na (size of ancestral population) parameters. To do this you can specify Relative parameters: True in config file.

You can also take theta0 by default equal to 1.0 and then rescale all parameters due to real value of theta0 after you receive demographic model.

I hope that will help.

Ekaterina
