### ISSUE TITLE
Folded SFS

### ISSUE THREAD

**Issue by deboraycb** [ctlab/GADMA#71]
Hi,

Thank you for developing GADMA! I have a few questions about using folded SFS. 

I am confused about whether I should input an already folded SFS and also use the `Outgroup: False` option in the param file or if I can provide an unfolded SFS (e.g. polarized by reference/alternative instead of ancestral/derived), and the option `Outgroup: False` will do the job of folding the sfs. In the example param file it says "#   If outgroup is False then SFS will be folded." so I understood the second option would be ok, but I wanted to confirm that. 

Also, when I try to provide an already folded SFS, I get this warning:
`WARNING:Spectrum_mod:Creating Spectrum with data_folded = True, but mask is not True for all entries which are nonsensical for a folded Spectrum.`
I think this is because I am not masking any of the sfs elements, and I should be masking the folded second half of the SFS, right?  I am generating the SFS from [ANGSD](https://github.com/ANGSD), and converting it to .fs format with a custom script, so my folded SFS just had the same number of elements as the unfolded, but half the elements were zeros. Should I mask those zeros with a "1" in the third line of the file? Or can I ignore this warning?

Sorry for a lot of questions together, but I think they are all related. Thanks again for a great tool!

**Comment by noscode** [comment]
Hi, @deboraycb 

Thank you very much for your interest and feedback. I hope I can help.

1) Yeah you are right, if you set `Outgroup: False` then the spectrum will be folded by GADMA automatically. You can also just to give folded spectrum and do not set `Outgroup` option at all. Then GADMA will read the data and check out if it is folded or not. You could check the value of the `Outgroup` field in the params file that GADMA creates and stored in the output directory.

2) The warning looks unusual and it comes from `dadi`/`moments` that are used to read data. It looks that you are correctly decided that it is because of the mask, at least I also think so. Unfortunately, I have not worked with ANGSD  but I know that there might be problems building SFS from it. One solution I know of is the [example](https://bitbucket.org/simongravel/moments/src/main/examples/fs_from_angsd/) from `moments` library. If I am correct there is a script (`parse_angsd_output.py`) to convert ANGSD output to spectrum. Maybe this can help you?

Best regards,
Ekaterina

**Comment by deboraycb** [comment]
That was very helpful, thanks for the quick reply! From that moments example it looks like the recommendation is to use unfolded SFS from ANGSD. It says:
"ANGSD should only be used to generate unfolded multidimensional spectra.
    If ancestral alleles are not available, alleles can be polarised from
    the reference sequence. In that case, the spectrum should be folded here.
    This retains more information than if one asks ANGSD to generate a folded
    spectrum."
Taken from here: https://bitbucket.org/simongravel/moments/src/e2d821b5bddb18e72d83532956159dcda29f482e/examples/fs_from_angsd/demog_infer_moments.py#lines-53:57

Providing an unfolded SFS from ANGSD (which I converted to fs) and Outgroup:False gave me no warnings!

**Comment by noscode** [comment]
Great! I am glad that it helped you.

**Comment by steigeec** [comment]
This issue has also been helpful for me, so thanks for this discussion!

To clarify on the question about masking: if we are reading in an unfolded sfs but specifying Outgroup: false so that GADMA folds the spectrum, should the second half of the sfs be masked (1) or unmasked (0)?

Thanks so much!

**Comment by noscode** [comment]
Hi @steigeec ,

I am glad that this issue turned out to be helpful!

If you specify Outgroup: False, then GADMA will fold the given spectrum and the half will be masked out (1).

You can check that it was done by looking at the generated pictures for your run: there will be a picture of SFS and its masked half will be in a white color.

Best regards,
Ekaterina

**Comment by steigeec** [comment]
Thanks so much for this explanation!
