### ISSUE TITLE
Specifying the number of time periods (final structure) for a single population

### ISSUE THREAD

**Issue by mrml500** [ctlab/GADMA#81]
Hi,

I am running GADMA (with dadi) to estimate changes in population size for a single population. So far, I have used this intial and final structure and have obtained realistic looking results:

> Initial structure: [1]
> Final structure: [7]

However, I chose to model 7 time periods somewhat arbitrarily. Is there a rule of thumb of what Final structure to input based on the data? e.g. effective sequence length, number of samples etc. ?

If there are too many time intervals then I assume there is a risk of overfitting? Or would inputting a large final structure value not matter as models with an excess number of time periods would not be selected?

Apologies if this is mentioned somewhere in the documentation or elsewhere.

Many thanks,
Mike

**Comment by noscode** [comment]
Hi Mike,

There are no explicit recommendations about the maximal number of time periods in the final structure. In ideal case Akaike information criterion (AIC) should catch overfitting. The problem is that SFS-based methods (dadi, moments, momi2 engines in GADMA) are not very reliable in case of a great number of parameters in the model (great number of the final structure).

It should be an interesting case using [7] as a final structure. If you run for 7 time intervals and the model with up to 5 intervals will be chosen as the best by AIC (or CLAIC) then I will consider that a reliable result. However, if the history with 7 time epochs is considered to be the best, then I will be not sure in it as it could be just a consequence of SFS-based method usage.

Best regards,
Ekaterina
